### ISSUE TITLE
Ablation for LSUN Church & Horse

### ISSUE THREAD

**Issue by hjinnkim** [jiwoogit/DCP-GAN#1]
Thank you for your great work!

I have a one question about ablation for LSUN Church & Horse on your paper.

You said CAGAN* is trained with StyleKD loss, and StyleKD is retrained with official code.

I guess the difference between those retrained models are whether they use parsing network or not. (CAGAN is trained with parsing network, and StyleKD is trained without parsing network.)

So, I want to ask you which parsing network did you use to train CAGAN with LSUN Church & LSUN horse

Thank your advance!

**Comment by jiwoogit** [comment]
Thank you for your interest!

As in section 4.1 of the paper, we utilize a **one-filled uniform mask** for training with LSUN Church and Horse due to the ambiguity in defining the image content.

Therefore, the difference between CAGAN* and StyleKD* lies **only in the initial weight** before the training stage (knowledge distillation stage).

Specifically, CAGAN* utilizes a partial part of the teacher synthesis network (ModConvs), while StyleKD* randomly initializing the synthesis network to address the output discrepancy problem.

Feel free to ask additional questions!

**Comment by hjinnkim** [comment]
Thank you for replying!

So as long as I understand, you utilize the Face Parsing Network for FFHQ dataset, and do not use Content Parsing for LSUN Church / Horse ? (one-filled uniform mask is same as no content parsing)

**Comment by jiwoogit** [comment]
> So as long as I understand, you utilize the Face Parsing Network for FFHQ dataset, and do not use Content Parsing for LSUN Church / Horse ? (one-filled uniform mask is same as no content parsing)

Yes, that's correct. Thank you.

**Comment by hjinnkim** [comment]
Thank you for your kind reply!

Again, big congrats for your CVPR 2024 acceptance!
